version: 2

sources:
  - name: src
    database: DBT
    schema: SRC
    description: "Source tables for the supply chain finance project"
    tables:

      - name: suppliers
        description: "Contains information about suppliers such as name, contact details, and address"
        columns:
          - name: supplier_id
            description: "Primary key for the supplier"
          - name: supplier_name
            description: "Name of the supplier"
          - name: contact_email
            description: "Email address of the supplier"
          - name: phone
            description: "Phone number of the supplier"
          - name: address
            description: "Physical address of the supplier"

      - name: products
        description: "Details about products that are ordered and supplied"
        columns:
          - name: product_id
            description: "Primary key for the product"
          - name: product_name
            description: "Name of the product"
          - name: category
            description: "Category the product belongs to"
          - name: unit_price
            description: "Price per unit of the product"

      - name: purchase_orders
        description: "Records of product purchase orders placed with suppliers"
        columns:
          - name: po_id
            description: "Primary key for the purchase order"
          - name: supplier_id
            description: "Foreign key to the supplier"
          - name: product_id
            description: "Foreign key to the product"
          - name: order_date
            description: "Date when the order was placed"
          - name: quantity
            description: "Quantity of product ordered"
          - name: unit_price
            description: "Unit price of the product at the time of order"
          - name: total_amount
            description: "Total cost for the order (quantity * unit_price)"

      - name: shipments
        description: "Tracks shipments made against purchase orders"
        columns:
          - name: shipment_id
            description: "Primary key for the shipment"
          - name: po_id
            description: "Foreign key to the purchase order"
          - name: shipment_date
            description: "Date of the shipment"
          - name: quantity
            description: "Quantity of product shipped"

      - name: invoices
        description: "Invoices generated against purchase orders"
        columns:
          - name: invoice_id
            description: "Primary key for the invoice"
          - name: po_id
            description: "Foreign key to the purchase order"
          - name: invoice_date
            description: "Date when the invoice was issued"
          - name: due_date
            description: "Date when the invoice payment is due"
          - name: amount_due
            description: "Total amount to be paid on the invoice"

      - name: payments
        description: "Payments made toward invoices"
        columns:
          - name: payment_id
            description: "Primary key for the payment"
          - name: invoice_id
            description: "Foreign key to the invoice"
          - name: payment_date
            description: "Date when the payment was made"
          - name: paid_amount
            description: "Amount that was paid"